
name: Terraform Apply
on: workflow_dispatch
jobs:
#   Terraform-Init:
#     runs-on: self-hosted
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - name: Terraform init
#         run: |
#           terraform init -backend-config=env-dev/state.tfvars
#
#   Terraform-Plan:
#     runs-on: self-hosted
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - name: Terraform init
#         run: |
#           terraform plan -var-file=env-dev/main.tfvars

    Terraform-Apply:
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Terraform Apply
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            terraform init -backend-config=env-dev/state.tfvars
            terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
            #terraform plan -var-file=env-dev/main.tfvars -var vault_token=${vault_token} 2>&1 | tail -n6 | head -n1 >$GITHUB_STEP_SUMMARY
          env:
            vault_token: ${{ secrets.vault_token }}

#    Helm-Install-Applications:
#      #needs: Terraform-Apply
#      runs-on: self-hosted
#      steps:
#        - name: Check out repository code
#          uses: actions/checkout@v4
#          with:
#            repository: genpactorg/roboshop-cart
#            path: app
#        - name: Check out repository code
#          uses: actions/checkout@v4
#          with:
#            repository: genpactorg/mas_roboshop_helm
#            path: helm
#        - name: Helm Install
#          run: |
#            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#            cd app
#            GID=$(git log --format="%H" -n 1)
#            cd ../helm
#            bash argocd.sh cart dev $GID





    Deploy-Cart:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-cart
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            echo $GID
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh cart dev $GID

    Deploy-Catalogue:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-catalogue
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh catalogue dev $GID

    Deploy-User:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-user
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh user dev $GID

    Deploy-Shipping:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-shipping
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh shipping dev $GID

    Deploy-Payment:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-payment
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh payment dev $GID

    Deploy-Frontend:
      needs: Terraform-Apply
      runs-on: self-hosted
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/roboshop-frontend
            path: app
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            repository: genpactorg/mas_roboshop_helm
            path: helm
        - name: Helm Install
          run: |
            export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
            cd app
            GID=$(git log --format="%H" -n 1)
            cd ../helm
            aws eks update-kubeconfig  --name dev
            bash argocd.sh frontend dev $GID
    
    
